# Stores drift thresholds and status

apiVersion: v1
kind: ConfigMap
metadata:
  name: drift-config
  namespace: default
data:
  data_drift_threshold: "0.05"
  model_drift_threshold: "0.10"
  last_drift_detected: "false"
  n steps:
    - - name: run-drift-check
        template: drift-check
    - - name: drift-check
        container:
        image: python:3.9-slim
        command: ["bash","-c"]
  args:
- pip install great_expectations && ge --v3-api checkpoint run my_drift_checkpoint && python /scripts/flag_drift.py --config /scripts/configmap-drift-config.yaml