# A CronWorkflow that runs daily to detect drift

apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: drift-detection
  namespace: default
spec:
  schedule: "@daily"
  concurrencyPolicy: "Allow"
  workflowSpec:
    entrypoint: detect-drift
    templates:
      - name: detect-drift