# A Workflow that triggers only when drift is flagged:
# The `flag_drift.py` updates the `drift-config` ConfigMap (`last_drift_detected`) based on GE results.

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: retraining
  namespace: default
spec:
  entrypoint: retrain-if-drift
  templates:
    - name: retrain-if-drift
      steps:
        - - name: check-flag
            template: read-flag
        - - name: run-retraining
            template: retrain
            when: "{{steps.check-flag.outputs.parameters.drift}} == 'true'"

    - name: read-flag
      script:
        image: bitnami/kubectl:latest
        command: ["sh", "-c"]
        source: |
          drift=$(kubectl get cm drift-config -o jsonpath='{.data.last_drift_detected}');
          echo "drift=$drift" > /tmp/output;
        volumeMounts:
          - name: workdir
            mountPath: /tmp
      outputs:
        parameters:
          - name: drift
            valueFrom:
              path: /tmp/output

    - name: retrain
      container:
        image: <your_training_image>
        command: ["python","/app/train.py"]
        args: ["--data-dir","/mnt/dataset","--mlflow-uri","http://mlflow:5000"]
  volumes:
    - name: workdir
      emptyDir: {}