FROM quay.io/jupyter/pytorch-notebook:cuda12-latest

USER ${NB_UID}

RUN pip install --pre --no-cache-dir lightning mlflow pynvml && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"