apiVersion: v1
kind: Secret
metadata:
  name: ghcr‑creds
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/credentials-type: docker
stringData:
  # your GHCR user + PAT with read/write on ghcr.io
  username: YOUR_GHCR_USERNAME
  password: YOUR_GHCR_PAT
