# k8s/overlays/canary/kustomization.yaml
namespace: canary
bases:
  - ../../base
patchesStrategicMerge:
  - patch-deployment.yaml
images:
  - name: ghcr.io/hurryingauto3/feature-service
    newTag: __TAG__