# k8s/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: feature-service
spec:
  selector:
    app: feature-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
