---
# - name: Install NVIDIA Docker GPG key
#   apt_key:
#     url: https://nvidia.github.io/nvidia-docker/gpgkey
#     state: present

# - name: Add NVIDIA Docker repository
#   apt_repository:
#     repo: "deb https://nvidia.github.io/libnvidia-container/ubuntu{{ ansible_distribution_release }}/$(ARCH) /"
#     state: present

# - name: Install nvidia-docker2 package
#   apt:
#     name: nvidia-docker2
#     state: present

# - name: Restart Docker to enable NVIDIA runtime
#   service:
#     name: docker
#     state: restarted

- name: Add NVIDIA Container Toolkit GPG key
  apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present

- name: Add NVIDIA Container Toolkit repository
  become: yes
  shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
      | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
      | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
      | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  args:
    executable: /bin/bash

- name: Install NVIDIA Container Toolkit
  apt:
    name: nvidia-container-toolkit
    state: latest
    update_cache: yes

- name: Configure Docker to use NVIDIA runtime
  shell: |
    nvidia-ctk runtime configure --runtime=docker
    systemctl restart docker
  args:
    executable: /bin/bash

