- hosts: all
  become: yes
  tasks:
    - name: Install base packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker engine & compose plugin
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
        state: latest

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add {{ ansible_user }} to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install NVIDIA Container Toolkit (GPU node only)
      block:
        - name: Add NVIDIA Docker GPG key
          apt_key:
            url: https://nvidia.github.io/nvidia-docker/gpgkey
            state: present
        - name: Add NVIDIA Docker repo
          apt_repository:
            repo: "deb https://nvidia.github.io/libnvidia-container/ubuntu{{ ansible_distribution_release }}/$(ARCH) /"
            state: present
        - name: Install nvidia-docker2
          apt:
            name: nvidia-docker2
            state: present
        - name: Restart Docker
          systemd:
            name: docker
            state: restarted
      when: inventory_hostname == 'gpu-node'