# Install and configure K3s cluster

- name: Install K3s control plane
  hosts: k8s_control_plane
  become: yes
  tasks:
    - name: Download K3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'
    - name: Install K3s (server)
      shell: |
        INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" \
        K3S_KUBECONFIG_MODE="644" \
        sh /tmp/k3s_install.sh server
    - name: Copy kubeconfig to home
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        mode: '644'

- name: Join K3s worker nodes
  hosts: k8s_workers
  become: yes
  vars:
    k3s_token: "{{ lookup('file', '/var/lib/rancher/k3s/server/node-token') }}"
    k3s_server: "https://{{ hostvars['services-node'].ansible_host }}:6443"
  tasks:
    - name: Download K3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'
    - name: Install K3s agent
      shell: |
        K3S_URL="{{ k3s_server }}" \
        K3S_TOKEN="{{ k3s_token }}" \
        sh /tmp/k3s_install.sh agent