#cloud-config
runcmd:
  # --- Update system ---
  - sudo apt-get update -y
  - sudo apt-get upgrade -y

  # --- Install base tools ---
  - sudo apt-get install -y wget curl git htop unzip build-essential python3-pip tmux jq

  # --- Install NVIDIA Driver + CUDA Toolkit ---
  - sudo apt-get install -y ubuntu-drivers-common
  - sudo ubuntu-drivers autoinstall
  - sudo apt-get install -y nvidia-cuda-toolkit
  - sudo reboot

  # --- Install Poetry (user level) ---
  - curl -sSL https://install.python-poetry.org | python3 -
  - echo 'export PATH="$HOME/.local/bin:$PATH"' >> /home/ubuntu/.bashrc

  # --- Clone GitHub project (adjust as needed) ---
  - mkdir -p /home/ubuntu/agriyield
  - cd /home/ubuntu/agriyield
  - git clone https://github.com/YOUR_USERNAME/agriyield.git .  # <-- change this

  # --- Set up Poetry project ---
  - export PATH="/home/ubuntu/.local/bin:$PATH"
  - poetry config virtualenvs.in-project true
  - poetry install

  # --- Allow MLflow port (5000) through firewall ---
  - sudo ufw allow 5000

final_message: "✅ AgriYield VM ready with Poetry, PyTorch (CUDA), and MLflow"