# k8s/overlays/production/kustomization.yaml
namespace: production
bases:
  - ../../base
patchesStrategicMerge:
  - patch-deployment.yaml
images:
  - name: ghcr.io/hurryingauto3/feature-service
    newTag: __TAG__