# roles/monitoring/tasks/main.yml
---
- name: Add Prometheus Helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    chart_ref: prometheus-community/kube-prometheus-stack
    release_name: mlops-monitoring
    namespace: monitoring
    create_namespace: true
    release_values: "{{ lookup('file', role_path + '/files/prometheus-values.yaml') | from_yaml }}"