# k8s/overlays/staging/patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-service
spec:
  template:
    spec:
      containers:
        - name: feature-service
          image: ghcr.io/hurryingauto3/feature-service:__TAG__
