scrape_configs:
  - job_name: 'model-serving'
    static_configs:
      - targets: ['model-serving:8000']

  - job_name: 'feature-serving'
    static_configs:
      - targets: ['feature-service:8001']

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:9095']