services:

  # --- ETL Job Service ---
  etl-download:
    build: ./extract
    container_name: etl-extract-container
    volumes:
      - /mnt/persistent/data_lake:/mnt/swift_store
    command:
      - poetry
      - run
      - python
      - /app/extract.py
      - ${GOOGLE_DRIVE_FOLDER_ID_HRRR}
      - ${GOOGLE_DRIVE_FOLDER_ID_USDA}
      - --clean
    environment:
      - OS_AUTH_URL=${OS_AUTH_URL}
      - OS_AUTH_TYPE=${OS_AUTH_TYPE}
      - OS_APPLICATION_CREDENTIAL_ID=${OS_APPLICATION_CREDENTIAL_ID}
      - OS_APPLICATION_CREDENTIAL_SECRET=${OS_APPLICATION_CREDENTIAL_SECRET}
      - OS_REGION_NAME=${OS_REGION_NAME}
      - GOOGLE_DRIVE_FOLDER_ID_HRRR=${GOOGLE_DRIVE_FOLDER_ID_HRRR}
      - GOOGLE_DRIVE_FOLDER_ID_USDA=${GOOGLE_DRIVE_FOLDER_ID_USDA}

  etl-transform:
    profiles: ["gpu"]
    build: ./transform
    container_name: etl-transform-container
    volumes:
      - /mnt/persistent/data_lake:/mnt/swift_store
    command:
      - poetry
      - run
      - python
      - /app/transform.py
      - --swift-container
      - ${FS_OPENSTACK_SWIFT_CONTAINER_NAME}
      - --clean
    environment:
      - OS_AUTH_URL=${OS_AUTH_URL}
      - OS_AUTH_TYPE=${OS_AUTH_TYPE}
      - OS_APPLICATION_CREDENTIAL_ID=${OS_APPLICATION_CREDENTIAL_ID}
      - OS_APPLICATION_CREDENTIAL_SECRET=${OS_APPLICATION_CREDENTIAL_SECRET}
      - OS_REGION_NAME=${OS_REGION_NAME}
      - FS_OPENSTACK_SWIFT_CONTAINER_NAME=${FS_OPENSTACK_SWIFT_CONTAINER_NAME}
