# devops/docker-compose/prometheus.yml
global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'model-serving'
    static_configs:
      - targets: ['model-serving:8000'] # Docker Compose service name and internal port
