---
- name: Create GHCR creds secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-creds
        namespace: argocd
        annotations:
          argocd-image-updater.argoproj.io/credentials-type: docker
      stringData:
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_pat }}"
