apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hurryingauto3/ece-gy-9183-mlops-project.git
    targetRevision: main
    path: charts/inference
  destination:
    server: https://kubernetes.default.svc
    namespace: inference-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
