apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference.fullname" . }}-canary
spec:
  selector:
    app: {{ include "inference.name" . }}
    version: stable       # initially same as stable
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
