- hosts: all
  become: yes
  vars:
    docker_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  tasks:
    - name: Install base packages for apt over HTTPS
      apt: 
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker apt repository
      apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present
    - name: Install Docker CE and Compose plugin
      apt: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
        state: latest
    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add Ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

- hosts: gpu
  become: yes
  tasks:
    - name: Install NVIDIA Docker runtime (for GPU support in containers)
      shell: |
        distribution=$(. /etc/os-release; echo $ID$VERSION_ID) && \
        curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add - && \
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list && \
        apt-get update && apt-get install -y nvidia-docker2 && systemctl restart docker
      args:
        executable: /bin/bash
      changed_when: false
